apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jetty-amq
  
parameters:
- description: The template service name, required
  name: SERVICE_NAME
  value: jetty-amq
  required: true
- description: A-MQ username, required
  name: AMQ_USERNAME
  required: true
- description: A-MQ password, required
  name: AMQ_PASSWORD
  required: true
- description: Maven release version
  name: RELEASE_VERSION
  value: 1.0-SNAPSHOT

objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's AMQP port.
    creationTimestamp: null
    labels:
      application: broker
      delete: amq
      template: amq62-basic
      xpaas: 1.2.0
    name: broker-amq-amqp
  spec:
    ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's OpenWire port.
    creationTimestamp: null
    labels:
      application: broker
      delete: amq
      template: amq62-basic
      xpaas: 1.2.0
    name: broker-amq-tcp
  spec:
    ports:
    - port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
    
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    creationTimestamp: null
    labels:
      component: ${SERVICE_NAME}
      container: java
      delete: amq
      version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}
  spec:
    ports:
    - port: 9102
      protocol: TCP
      targetPort: 8080
    selector:
      component: ${SERVICE_NAME}-input
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
    
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      component: ${SERVICE_NAME}
      container: java
      delete: amq
      version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}-route
  spec:
    to:
      kind: Service
      name: ${SERVICE_NAME}
  status: {}
  
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      component: ${SERVICE_NAME}-input
      container: java
      delete: amq
      group: quickstarts
      project: ${SERVICE_NAME}-input
      provider: s2i
      version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}-input
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SERVICE_NAME}-input:latest
    resources: {}
    source:   
      git:
        ref: master
        uri: https://github.com/benemon/camel-amq-example
      contextDir: input
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
        - name: ARTIFACT_DIR
        - name: MAVEN_ARGS
          value: package -DskipTests -e
        - name: MAVEN_ARGS_APPEND
        - name: RELEASE_VERSION
          value: ${RELEASE_VERSION}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:1.0
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0

- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      component: ${SERVICE_NAME}-output
      container: java
      delete: amq
      group: quickstarts
      project: ${SERVICE_NAME}-output
      provider: s2i
      version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}-output
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SERVICE_NAME}-output:latest
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/benemon/camel-amq-example
      contextDir: output
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
        - name: ARTIFACT_DIR
        - name: MAVEN_ARGS
          value: package -DskipTests -e
        - name: MAVEN_ARGS_APPEND
        - name: RELEASE_VERSION
          value: ${RELEASE_VERSION}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:1.0
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
    
        
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2016-03-07T16:25:19Z
    creationTimestamp: null
    labels:
      component: ${SERVICE_NAME}-input
      container: java
      delete: amq
      version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}-input
    
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2016-03-07T16:25:19Z
    creationTimestamp: null
    labels:
      component: ${SERVICE_NAME}-output
      container: java
      delete: amq
      version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}-output
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      application: broker
      delete: amq
      template: amq62-basic
      xpaas: 1.2.0
    name: broker-amq
  spec:
    replicas: 1
    selector:
      deploymentConfig: broker-amq
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: broker
          deploymentConfig: broker-amq
        name: broker-amq
      spec:
        containers:
        - env:
          - name: AMQ_USER
            value: ${AMQ_USERNAME}
          - name: AMQ_PASSWORD
            value: ${AMQ_PASSWORD}
          - name: AMQ_TRANSPORTS
            value: openwire,amqp
          - name: AMQ_QUEUES
          - name: AMQ_TOPICS
          - name: AMQ_MESH_DISCOVERY_TYPE
            value: kube
          - name: AMQ_MESH_SERVICE_NAME
            value: broker-amq-tcp
          - name: AMQ_MESH_SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: AMQ_STORAGE_USAGE_LIMIT
            value: 100 gb
          image: registry.access.redhat.com/jboss-amq-6/amq62-openshift:1.2
          imagePullPolicy: Always
          name: broker-amq
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 1883
            name: mqtt
            protocol: TCP
          - containerPort: 61613
            name: stomp
            protocol: TCP
          - containerPort: 61616
            name: tcp
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/amq/bin/readinessProbe.sh
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - broker-amq
        from:
          kind: ImageStreamTag
          name: jboss-amq-62:1.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status: {}
  
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
         component: ${SERVICE_NAME}-input
         container: java
         deploymentconfig: ${SERVICE_NAME}-input
         version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}-input
  spec:
    replicas: 1
    selector:
          component: ${SERVICE_NAME}-input
          container: java
          deploymentconfig: ${SERVICE_NAME}-input
          version: 2.2.0.redhat-079
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: ${SERVICE_NAME}-input
          container: java
          deploymentconfig: ${SERVICE_NAME}-input
          version: 2.2.0.redhat-079
      spec:
        containers:
        - env:
          - name: BROKER_AMQ_TCP_USERNAME
            value: ${AMQ_USERNAME}
          - name: BROKER_AMQ_TCP_PASSWORD
            value: ${AMQ_PASSWORD}
          - name: BROKER_AMQ_AMQP_USERNAME
            value: ${AMQ_USERNAME}
          - name: BROKER_AMQ_AMQP_PASSWORD
            value: ${AMQ_PASSWORD}
          image: ${SERVICE_NAME}-input
          imagePullPolicy: Always
          name: ${SERVICE_NAME}-input
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - (curl -f 127.0.0.1:8080/readiness) >/dev/null 2>&1; test $? != 7
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}-input
        from:
          kind: ImageStream
          name: ${SERVICE_NAME}-input
      type: ImageChange
    - type: ConfigChange
  status: {}
  
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
         component: ${SERVICE_NAME}-output
         container: java
         deploymentconfig: ${SERVICE_NAME}-output
         version: 2.2.0.redhat-079
    name: ${SERVICE_NAME}-output
  spec:
    replicas: 1
    selector:
          component: ${SERVICE_NAME}-output
          container: java
          deploymentconfig: ${SERVICE_NAME}-output
          version: 2.2.0.redhat-079
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: ${SERVICE_NAME}-output
          container: java
          deploymentconfig: ${SERVICE_NAME}-output
          version: 2.2.0.redhat-079
      spec:
        containers:
        - env:
          - name: BROKER_AMQ_TCP_USERNAME
            value: ${AMQ_USERNAME}
          - name: BROKER_AMQ_TCP_PASSWORD
            value: ${AMQ_PASSWORD}
          - name: BROKER_AMQ_AMQP_USERNAME
            value: ${AMQ_USERNAME}
          - name: BROKER_AMQ_AMQP_PASSWORD
            value: ${AMQ_PASSWORD}
          image: ${SERVICE_NAME}-output
          imagePullPolicy: Always
          name: ${SERVICE_NAME}-output
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - (curl -f 127.0.0.1:8080/readiness) >/dev/null 2>&1; test $? != 7
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}-output
        from:
          kind: ImageStream
          name: ${SERVICE_NAME}-output
      type: ImageChange
    - type: ConfigChange
  status: {}